import { useEffect, useRef, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, ChevronDown, ChevronRight, ChevronsRight, Clock3, Copy, Download, Expand, FileText, FlipHorizontal2, CodeXml, Keyboard, Laptop, Menu, Monitor, MoreHorizontal, Pause, Play, Plus, RotateCcw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { defaults, importScripts, normalizeSettings, seedScripts, timeLabel, validScripts, words } from './model';
import type { Script, Settings } from './model';
import { useStudioTools } from './webmcp';

declare global { interface Window { cueflowDesktop?: {platform:string;setFullscreen:(value:boolean)=>Promise<void>;getFullscreen:()=>Promise<boolean>;onFullscreenChange:(callback:(value:boolean)=>void)=>()=>void} } }
const repo='https://github.com/mrHeinrichh/cueflow';
function readLibrary() { try {const raw=localStorage.getItem('cueflow.scripts');if(raw){const data=JSON.parse(raw);if(validScripts(data))return data;}}catch{} return seedScripts; }
function readSettings() {try{return normalizeSettings(JSON.parse(localStorage.getItem('cueflow.settings')||'{}'));}catch{return defaults;}}
function downloadFile(name:string,content:string,type='text/plain') {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Brand() {return <span className="brand"><span className="brand-mark"><ChevronsRight size={23}/></span>CueFlow<span className="brand-dot">.</span></span>;}
function IconButton({label,children,onClick,active=false,disabled=false}:{label:string;children:ReactNode;onClick:()=>void;active?:boolean;disabled?:boolean}) {return <button type="button" className={`icon-btn ${active?'active':''}`} title={label} aria-label={label} aria-pressed={active} onClick={onClick} disabled={disabled}>{children}</button>;}
function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(value:number)=>void}) {return <label className="range-field"><span>{label}<output>{value}{unit}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} style={{'--range-progress':`${(value-min)/(max-min)*100}%`} as CSSProperties}/></label>;}
function Toggle({label,detail,checked,onChange,icon}:{label:string;detail?:string;checked:boolean;onChange:()=>void;icon:ReactNode}) {return <button className="toggle-row" type="button" role="switch" aria-checked={checked} onClick={onChange}><span className="toggle-icon">{icon}</span><span className="toggle-label">{label}{detail&&<small>{detail}</small>}</span><span className={`toggle ${checked?'checked':''}`}><span/></span></button>;}

export default function App() {
 const [route,setRoute]=useState(location.hash==='#/download'?'download':'studio');
 const [scripts,setScripts]=useState<Script[]>(readLibrary);
 const [activeId,setActiveId]=useState(scripts[0].id);
 const [settings,setSettings]=useState<Settings>(readSettings);
 const [query,setQuery]=useState('');
 const [tab,setTab]=useState<'preview'|'edit'>('preview');
 const [playing,setPlaying]=useState(false);
 const [countdown,setCountdown]=useState<number|null>(null);
 const [elapsed,setElapsed]=useState(0);
 const [progress,setProgress]=useState(0);
 const [full,setFull]=useState(false);
 const [sidebar,setSidebar]=useState(false);
 const [controls,setControls]=useState(false);
 const [modal,setModal]=useState<'shortcuts'|'delete'|'privacy'|null>(null);
 const [menu,setMenu]=useState(false);
 const [toast,setToast]=useState('');
 const [saveError,setSaveError]=useState(false);
 const viewport=useRef<HTMLDivElement>(null);
 const stage=useRef<HTMLDivElement>(null);
 const fileInput=useRef<HTMLInputElement>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const offset=useRef(0);
 const active=scripts.find(s=>s.id===activeId)||scripts[0];
 const playingRef=useRef(playing); playingRef.current=playing;
 const settingsRef=useRef(settings);settingsRef.current=settings;
 const notify=(message:string)=>setToast(message);
 const update=(patch:Partial<Settings>)=>setSettings(s=>({...s,...patch}));
 const pause=()=>{setPlaying(false);setCountdown(null);};
 const reset=()=>{pause();if(viewport.current)viewport.current.scrollTop=0;offset.current=0;setElapsed(0);setProgress(0);};
 const togglePlay=()=>{if(playing||countdown!==null){pause();return;}if(!active.content.trim()){notify('Add a few words to your script first.');setTab('edit');return;}setTab('preview');if(progress>=99.9){if(viewport.current)viewport.current.scrollTop=0;offset.current=0;setElapsed(0);setProgress(0);}if(settings.countdown>0&&elapsed===0)setCountdown(Math.round(settings.countdown));else setPlaying(true);};
 const selectScript=(id:string)=>{reset();setActiveId(id);setSidebar(false);};
 const editScript=(patch:Partial<Script>)=>{pause();setScripts(all=>all.map(s=>s.id===active.id?{...s,...patch,updated:Date.now()}:s));};
 const createScript=()=>{if(scripts.length>=500){notify('Your library has reached 500 scripts. Export a backup and remove a few scripts first.');return;}const script={id:crypto.randomUUID(),title:'Untitled script',content:'',updated:Date.now()};setScripts(s=>[script,...s]);selectScript(script.id);setTab('edit');location.hash='/studio';};
 const fullscreen=async()=>{try{if(window.cueflowDesktop){await window.cueflowDesktop.setFullscreen(!full);setFull(!full);}else if(document.fullscreenElement){await document.exitFullscreen();}else{await stage.current?.requestFullscreen();}}catch{notify('Fullscreen is unavailable here. Try the desktop app or another browser.');}};
 useEffect(()=>{const onHash=()=>{reset();setRoute(location.hash==='#/download'?'download':'studio');};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
 useEffect(()=>{try{localStorage.setItem('cueflow.scripts',JSON.stringify(scripts));setSaveError(false);}catch{setSaveError(true);}},[scripts]);
 useEffect(()=>{try{localStorage.setItem('cueflow.settings',JSON.stringify(settings));}catch{notify('Display settings could not be saved on this device.');}},[settings]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
 useEffect(()=>{if(countdown===null)return;const id=setTimeout(()=>{if(countdown<=1){setCountdown(null);setPlaying(true);}else setCountdown(countdown-1);},1000);return()=>clearTimeout(id);},[countdown]);
 useEffect(()=>{const onFull=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',onFull);const remove=window.cueflowDesktop?.onFullscreenChange(setFull);return()=>{document.removeEventListener('fullscreenchange',onFull);remove?.();};},[]);
 useEffect(()=>{const onHidden=()=>{if(document.hidden)pause();};document.addEventListener('visibilitychange',onHidden);return()=>document.removeEventListener('visibilitychange',onHidden);},[]);
 useEffect(()=>{if(!playing)return;let frame=0,last=0,total=0;const tick=(now:number)=>{const el=viewport.current;if(!el)return;if(last){const delta=Math.min((now-last)/1000,.1);total+=delta;offset.current+=settingsRef.current.speed*delta;el.scrollTop=offset.current;const max=el.scrollHeight-el.clientHeight;if(total>=.1){setElapsed(t=>t+total);total=0;setProgress(max>0?Math.min(100,el.scrollTop/max*100):100);}if(el.scrollTop>=max-1){setPlaying(false);setProgress(100);return;}}last=now;frame=requestAnimationFrame(tick);};offset.current=viewport.current?.scrollTop||0;frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing]);
 useEffect(()=>{let lock:WakeLockSentinel|undefined;let cancelled=false;if(playing&&'wakeLock'in navigator)navigator.wakeLock.request('screen').then(v=>{if(cancelled)void v.release();else lock=v;}).catch(()=>{});return()=>{cancelled=true;void lock?.release();};},[playing]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement; if(route!=='studio'||modal||target.closest('input,textarea,select,[contenteditable="true"]')||e.metaKey||e.ctrlKey||e.altKey)return;if(e.code==='Space'&&!target.closest('button,a')){e.preventDefault();togglePlay();}if(e.key==='Escape'){pause();setMenu(false);setSidebar(false);setControls(false);}if(e.key==='ArrowUp'){e.preventDefault();setSettings(s=>({...s,speed:Math.min(120,s.speed+5)}));}if(e.key==='ArrowDown'){e.preventDefault();setSettings(s=>({...s,speed:Math.max(10,s.speed-5)}));}if(e.key==='?')setModal('shortcuts');if(e.key==='/'){e.preventDefault();document.querySelector<HTMLInputElement>('[aria-label="Search scripts"]')?.focus();}if(e.key.toLowerCase()==='r')reset();if(e.key.toLowerCase()==='m')setSettings(s=>({...s,mirror:!s.mirror}));if(e.key.toLowerCase()==='f'){setTab('preview');setTimeout(()=>void fullscreen(),0);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
 const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>(file.name.toLowerCase().endsWith('.json')?32000000:2000000))throw new Error('Choose a script under 2 MB or a backup under 32 MB.');const imported=importScripts(await file.text(),file.name);if(scripts.length+imported.length>500)throw new Error('Your library can hold up to 500 scripts.');setScripts(s=>[...imported,...s]);selectScript(imported[0].id);notify(`Imported ${imported.length===1?'your script':`${imported.length} scripts`}.`);}catch(e){notify(e instanceof Error?e.message:'This file could not be imported.');}finally{if(fileInput.current)fileInput.current.value='';}};
 const backup=()=>{downloadFile('cueflow-library.json',JSON.stringify({version:1,scripts},null,2),'application/json');notify('Library backup downloaded.');};
 const exportScript=()=>{downloadFile(`${active.title.replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,80)||'script'}.txt`,active.content);setMenu(false);notify('Script exported.');};
 const duplicate=()=>{if(scripts.length>=500){notify('Your library has reached 500 scripts.');return;}const copy={...active,id:crypto.randomUUID(),title:`${active.title} (copy)`,updated:Date.now()};setScripts(s=>[copy,...s]);selectScript(copy.id);setMenu(false);notify('Script duplicated.');};
 const removeScript=()=>{const remaining=scripts.filter(s=>s.id!==active.id);if(!remaining.length)remaining.push({id:crypto.randomUUID(),title:'Untitled script',content:'',updated:Date.now()});setScripts(remaining);selectScript(remaining[0].id);setModal(null);notify('Script deleted.');};
 useStudioTools(scripts, active.id, selectScript);
 const count=words(active.content);
 return <><div className={`app-shell ${route==='download'?'download-shell':''}`}>
  <aside className={`sidebar ${sidebar?'mobile-open':''}`}>
   <a href="#/studio" className="brand-link" aria-label="CueFlow studio"><Brand/></a>
   <div className="workspace-label"><span className="workspace-avatar">Y</span><div>Your workspace<small>Personal studio</small></div><ChevronDown size={16}/></div>
   <button className="new-script" onClick={createScript}><Plus size={18}/>New script<span>+</span></button>
   <nav className="main-nav"><a className={route==='studio'?'selected':''} href="#/studio"><FileText size={18}/>My scripts<span>{scripts.length}</span></a><a className={route==='download'?'selected':''} href="#/download"><Laptop size={18}/>Desktop app<ArrowDownToLine size={15}/></a></nav>
   <div className="library-heading"><span>YOUR SCRIPTS</span><IconButton label="Import script" onClick={()=>fileInput.current?.click()}><Upload size={16}/></IconButton></div>
   <label className="search-field"><Search size={15}/><input aria-label="Search scripts" placeholder="Find a script..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></label>
   <div className="script-list">{scripts.filter(s=>s.title.toLowerCase().includes(query.toLowerCase())).map(s=><button key={s.id} className={`script-item ${s.id===active.id?'chosen':''}`} onClick={()=>{selectScript(s.id);location.hash='/studio';}}><FileText size={17}/><span>{s.title||'Untitled script'}<small>{words(s.content)} words · {Math.max(1,Math.ceil(words(s.content)/130))} min</small></span>{s.id===active.id&&<span className="selected-dot"/>}</button>)}{!scripts.some(s=>s.title.toLowerCase().includes(query.toLowerCase()))&&<p className="empty-search">No matching scripts.</p>}</div>
   <div className="sidebar-bottom"><div className="local-note"><ShieldCheck size={18}/><span>A little space of your own<small>Scripts stay on this device.</small></span></div><button className="sidebar-link" onClick={backup}><Download size={16}/>Back up library</button><button className="sidebar-link" onClick={()=>setModal('shortcuts')}><Keyboard size={16}/>Keyboard shortcuts<kbd>?</kbd></button><div className="sidebar-footer"><span className="user-avatar">Y</span><span>Your creative space<small>CueFlow v1.0</small></span><button aria-label="Privacy information" className="plain-icon" onClick={()=>setModal('privacy')}><ShieldCheck size={17}/></button></div></div>
  </aside>
  {sidebar&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
  <main className="main-content">
   <header className="topbar"><div className="breadcrumb"><button className="mobile-menu plain-icon" aria-label="Open navigation" onClick={()=>setSidebar(true)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{route==='studio'?'My scripts':'Desktop app'}</strong></div><div className="topbar-right"><span className="local-badge"><span/>Local-first. Always.</span><a href={repo} target="_blank" rel="noreferrer" className="top-github" aria-label="View source on GitHub"><CodeXml size={18}/></a></div></header>
   {route==='download'?<DownloadPage/>:<div className="studio-content">
    <div className="page-heading"><div><div className="eyebrow">MAKE EVERY WORD COUNT</div><h1>Your next great take starts here<span>.</span></h1><p>Find your words. Set your pace. Let the rest flow.</p></div><button className="button secondary import-top" onClick={()=>fileInput.current?.click()}><Upload size={16}/>Import script</button></div>
    {saveError&&<div className="save-warning" role="alert">Your changes could not be saved. Download a backup to keep your scripts safe.<button onClick={backup}>Download backup</button></div>}
    <div className="studio-grid">
     <section className="script-workspace" aria-label="Teleprompter workspace">
      <div className="script-toolbar"><div className="script-title"><span className="document-icon"><FileText size={19}/></span><div><h2>{active.title||'Untitled script'}</h2><span>{count} words<span className="meta-dot">·</span>~{Math.max(1,Math.ceil(count/130))} min read</span></div></div><div className="document-actions"><span className={`saved ${saveError?'failed':''}`}><Check size={13}/>{saveError?'Not saved':'Saved locally'}</span><div className="menu-wrap"><IconButton label="Script actions" onClick={()=>setMenu(!menu)}><MoreHorizontal size={21}/></IconButton>{menu&&<><button className="menu-scrim" aria-label="Close script actions" onClick={()=>setMenu(false)}/><div className="dropdown"><button onClick={duplicate}><Copy size={16}/>Duplicate script</button><button onClick={exportScript}><Download size={16}/>Export as text</button><button className="danger" onClick={()=>{setMenu(false);pause();setModal('delete');}}><Trash2 size={16}/>Delete script</button></div></>}</div></div></div>
      <div className="view-toolbar"><div className="segmented" role="tablist" aria-label="Script view"><button role="tab" aria-selected={tab==='preview'} className={tab==='preview'?'selected':''} onClick={()=>setTab('preview')}><Monitor size={15}/>Prompter</button><button role="tab" aria-selected={tab==='edit'} className={tab==='edit'?'selected':''} onClick={()=>{reset();setTab('edit');}}><FileText size={15}/>Edit script</button></div><button className="mobile-settings button small" onClick={()=>setControls(!controls)}><SlidersHorizontal size={16}/>Settings</button><span className="preview-label">{tab==='edit'?'Make it sound like you':'A little practice. A lot of confidence.'}</span></div>
      {tab==='edit'?<div className="editor"><label>Script title<input maxLength={120} value={active.title} onChange={e=>editScript({title:e.target.value})} placeholder="Give your script a title"/></label><label className="content-label">Your words<textarea aria-label="Script content" value={active.content} maxLength={500000} onChange={e=>{editScript({content:e.target.value});offset.current=0;setProgress(0);setElapsed(0);}} placeholder="Start with an idea. Paste your script here, or write something new…" spellCheck/></label><div className="editor-footer"><span>Plain text · Automatically saved on this device</span><span>{count} words</span></div></div>:<div ref={stage} className={`prompter-stage ${settings.theme==='light'?'light':''} ${full?'is-fullscreen':''}`}>
       <div className="stage-top"><span className={`stage-status ${playing?'running':''}`}><span/>{countdown!==null?'GET READY':playing?'IN YOUR FLOW':progress>=99.9?'THAT’S A WRAP':'READY WHEN YOU ARE'}</span><span>{settings.mirror?'MIRRORED VIEW':'LIVE PREVIEW'}</span></div>
       {settings.guide&&<div className="reading-guide"><span/></div>}
       <div className="prompter-viewport" ref={viewport} tabIndex={0} aria-label="Teleprompter script. Space to play or pause." onScroll={()=>{if(!playingRef.current&&viewport.current){offset.current=viewport.current.scrollTop;const max=viewport.current.scrollHeight-viewport.current.clientHeight;setProgress(max>0?Math.min(100,offset.current/max*100):0);}}} onWheel={()=>{if(playing)pause();}} onTouchStart={()=>{if(playing)pause();}}>
        <div className={`prompt-text ${settings.mirror?'mirrored':''}`} style={{'--prompt-size':`${settings.fontSize}px`,lineHeight:settings.lineHeight,width:`${settings.width}%`} as CSSProperties}>{active.content.trim()?active.content.split('\n\n').map((p,i)=><p key={i}>{p}</p>):<p className="prompt-empty">Your story goes here.<br/><small>Open “Edit script” to add your words.</small></p>}</div>
       </div>
       <div className="stage-fade"/>
       {countdown!==null&&<button className="countdown" aria-label="Cancel countdown" onClick={pause}><strong>{countdown}</strong><span>Take a breath. You’re up next.</span><small>Click to cancel</small></button>}
       <div className="stage-bottom"><span><Clock3 size={14}/>{timeLabel(elapsed)}</span><span>{Math.round(progress)}% complete</span><button onClick={fullscreen} aria-label={full?'Exit fullscreen':'Enter fullscreen'} title="Fullscreen (F)"><Expand size={17}/></button></div>
       {full&&<div className="fullscreen-controls"><button onClick={reset} aria-label="Restart script"><RotateCcw size={21}/></button><button className="full-play" onClick={togglePlay}>{playing||countdown!==null?<Pause/>:<Play/>}{playing||countdown!==null?'Pause':'Start reading'}</button><button onClick={fullscreen} aria-label="Exit fullscreen"><X size={22}/></button></div>}
      </div>}
      <div className="transport"><div className="transport-left"><IconButton label="Restart script (R)" onClick={reset}><RotateCcw size={18}/></IconButton><span className="transport-divider"/><span className="pace"><strong>{settings.speed}</strong> px/s</span></div><button className={`play-button ${playing||countdown!==null?'playing':''}`} onClick={togglePlay}>{playing||countdown!==null?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}{countdown!==null?'Cancel countdown':playing?'Pause reading':progress>=99.9?'Read again':'Start reading'}<kbd>Space</kbd></button><div className="transport-right"><IconButton label="Mirror text (M)" onClick={()=>update({mirror:!settings.mirror})} active={settings.mirror}><FlipHorizontal2 size={19}/></IconButton><IconButton label="Fullscreen (F)" onClick={()=>{setTab('preview');setTimeout(()=>void fullscreen(),0);}}><Expand size={18}/></IconButton></div></div>
      <div className="progress-track" aria-label="Reading progress" role="progressbar" aria-valuenow={Math.round(progress)} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${progress}%`}}/></div>
     </section>
     <aside className={`settings-panel ${controls?'settings-open':''}`} aria-label="Prompter settings"><div className="settings-title"><span><SlidersHorizontal size={18}/>Make it yours</span><IconButton label="Reset display settings" onClick={()=>{setSettings(defaults);notify('Display settings reset.');}}><RotateCcw size={15}/></IconButton></div><div className="settings-section"><h3>READING PACE</h3><Range label="Scroll speed" value={settings.speed} min={10} max={120} unit=" px/s" onChange={v=>update({speed:v})}/><div className="range-hints"><span>Take it slow</span><span>Pick it up</span></div><label className="select-field"><span><Clock3 size={16}/>Start countdown</span><select aria-label="Start countdown" value={settings.countdown} onChange={e=>update({countdown:Number(e.target.value)})}><option value={0}>Off</option><option value={3}>3 sec</option><option value={5}>5 sec</option><option value={10}>10 sec</option></select></label></div><div className="settings-section"><h3>TEXT & SPACING</h3><Range label="Text size" value={settings.fontSize} min={24} max={80} unit=" px" onChange={v=>update({fontSize:v})}/><Range label="Line spacing" value={settings.lineHeight} min={1.2} max={2.2} step={.1} unit="×" onChange={v=>update({lineHeight:v})}/><Range label="Text width" value={settings.width} min={45} max={95} unit="%" onChange={v=>update({width:v})}/></div><div className="settings-section display-settings"><h3>DISPLAY</h3><Toggle icon={<FlipHorizontal2 size={17}/>} label="Mirror mode" detail="For teleprompter glass" checked={settings.mirror} onChange={()=>update({mirror:!settings.mirror})}/><Toggle icon={<Settings2 size={17}/>} label="Reading guide" detail="Keep your place" checked={settings.guide} onChange={()=>update({guide:!settings.guide})}/><div className="theme-field"><span>Background</span><div><button className={`theme-swatch dark ${settings.theme==='dark'?'chosen':''}`} aria-label="Dark prompter background" aria-pressed={settings.theme==='dark'} onClick={()=>update({theme:'dark'})}>{settings.theme==='dark'&&<Check size={14}/>}</button><button className={`theme-swatch light ${settings.theme==='light'?'chosen':''}`} aria-label="Light prompter background" aria-pressed={settings.theme==='light'} onClick={()=>update({theme:'light'})}>{settings.theme==='light'&&<Check size={14}/>}</button></div></div></div><div className="settings-tip"><Sparkles size={17}/><p>A natural delivery starts with a comfortable pace. Try a quick practice run.</p></div></aside>
    </div>
    <div className="below-workspace"><span><ShieldCheck size={15}/>Your words stay yours. Saved on this device, never uploaded.</span><button onClick={()=>setModal('shortcuts')}><Keyboard size={16}/>Shortcuts<ArrowRight size={14}/></button></div>
    <a href="#/download" className="desktop-banner"><span className="banner-icon"><Laptop size={24}/></span><span><strong>Your studio, even when you’re offline.</strong><small>Get CueFlow for macOS and Windows. Same flow. Your own space.</small></span><span className="banner-link">Get the desktop app<ArrowUpRightIcon/></span></a>
   </div>}
  </main>
 </div>
 <input ref={fileInput} type="file" accept=".txt,.md,.json" className="visually-hidden" aria-label="Import script file" onChange={e=>void importFile(e.target.files?.[0])}/>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}}><div className="dialog-body"><button className="dialog-close icon-btn" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={21}/></button>{modal==='shortcuts'?<><Keyboard className="dialog-symbol" size={29}/><h2>Keep your hands in the flow.</h2><p>Shortcuts work outside the script editor and form fields.</p><div className="shortcut-list">{[['Play / pause','Space'],['Faster / slower','↑ / ↓'],['Restart script','R'],['Mirror text','M'],['Toggle fullscreen','F'],['Pause / cancel countdown','Esc']].map(([label,key])=><div key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div></>:modal==='delete'?<><Trash2 className="dialog-symbol" size={29}/><h2>Delete this script?</h2><p>“{active.title}” will be removed from this device. Export a copy first if you want to keep it.</p><div className="dialog-actions"><button className="button secondary" onClick={()=>setModal(null)}>Keep script</button><button className="button destructive" onClick={removeScript}>Delete script</button></div></>:<><ShieldCheck className="dialog-symbol" size={29}/><h2>Your words stay yours.</h2><p>CueFlow stores scripts and display settings in local storage on this device. It has no account system, analytics, microphone access, or script uploads.</p><p>The browser and desktop app keep separate libraries. Use “Back up library” and “Import script” to move your scripts between them. Clearing browser data can remove your scripts, so keep a backup of important work.</p><p>The website host may keep standard request logs. GitHub handles desktop downloads.</p><button className="button primary" onClick={()=>{backup();setModal(null);}}>Back up my library</button></>}</div></dialog>
 {toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 </>;
}
function ArrowUpRightIcon(){return <ArrowRight size={17} style={{transform:'rotate(-35deg)'}}/>;}
function DownloadPage(){const base=`${repo}/releases/download/v1.0.0`;return <div className="download-page"><div className="download-eyebrow"><span/> YOUR WORDS. YOUR RHYTHM.</div><h1>A little less thinking.<br/>A lot more <em>flow.</em></h1><p className="download-lede">Meet your new on-camera companion. A focused teleprompter that lets you be present, sound natural, and make every take your own.</p><div className="download-hero-actions"><a className="button primary" href="#/studio"><Play size={17} fill="currentColor"/>Open the web studio<ArrowRight size={17}/></a><span>No account. No distractions.</span></div><div className="download-rule"><span>TAKE YOUR STUDIO WITH YOU</span><span>VERSION 1.0.0</span></div><div className="download-cards"><article><span className="os-icon"><Laptop size={32}/></span><h2>Made for your Mac.</h2><p>Your scripts and your rhythm, right at home on macOS.</p><a className="button primary" href={`${base}/CueFlow-1.0.0-mac-arm64.dmg`}><Download size={18}/>Download for Apple Silicon</a><a className="secondary-download" href={`${base}/CueFlow-1.0.0-mac-x64.dmg`}>Intel Mac download<ArrowRight size={15}/></a><small>macOS 13 or later · Apple Silicon & Intel</small></article><article><span className="os-icon"><Monitor size={32}/></span><h2>At home on Windows.</h2><p>From your first practice run to your best take yet.</p><a className="button dark-button" href={`${base}/CueFlow-1.0.0-win-x64.exe`}><Download size={18}/>Download for Windows</a><span className="secondary-download">A simple installer. A focused workspace.</span><small>Windows 10 or later · 64-bit</small></article></div><div className="release-note"><ShieldCheck size={21}/><div><strong>A note about these first desktop releases</strong><p>These builds are unsigned. macOS and Windows may show a security warning because they don’t yet have a verified publisher certificate. Only download the files from this project’s <a href={`${repo}/releases/tag/v1.0.0`} target="_blank" rel="noreferrer">GitHub release</a>. You can also use the web studio without installing anything.</p></div></div><div className="feature-row">{[[<SlidersHorizontal size={22}/>, 'Set your own pace','Fine-tune scrolling, type size, and spacing.'],[<FlipHorizontal2 size={22}/>, 'Ready for your setup','Mirror mode and a clean fullscreen view.'],[<ShieldCheck size={22}/>, 'Keep your words close','Offline desktop use. Local script storage.']].map(([icon,title,desc],i)=><div key={i}>{icon}<h3>{title}</h3><p>{desc}</p></div>)}</div><footer className="download-footer"><Brand/><span>Made for the moments you have something to say.</span><a href={repo} target="_blank" rel="noreferrer"><CodeXml size={16}/>View on GitHub</a></footer></div>;}
