export type Script = { id: string; title: string; content: string; updated: number };
export type Settings = { speed: number; fontSize: number; lineHeight: number; width: number; mirror: boolean; guide: boolean; countdown: number; theme: 'dark' | 'light' };
export const defaults: Settings = { speed: 42, fontSize: 44, lineHeight: 1.7, width: 80, mirror: false, guide: true, countdown: 3, theme: 'dark' };
export const welcome = `Take a breath.\nYou’ve got this.\n\nEvery great story starts with a single idea. A moment of curiosity. A different way of seeing the world.\n\nToday, I want to share something I’ve been working on — and why it matters to me.\n\nThe best part of creating isn’t getting every word perfect. It’s finding the words that feel like you.\n\nSo slow down. Leave a little space between your thoughts. Look up, and let your personality come through.\n\nYou don’t need to be anyone else.\nYou just need to start.\n\nThanks for being here. Let’s make something worth sharing.`;
export const seedScripts: Script[] = [
 {id:'welcome', title:'Your next great take',content:welcome,updated:Date.now()},
 {id:'intro',title:'A quick introduction',content:'Hey everyone, welcome back.\n\nIf we haven’t met, I’m [your name], and this is where I share [your topic].\n\nToday, we’re diving into something I get asked about all the time.\n\nHere are three things I wish I’d known when I started.\n\nFirst, keep it simple. Focus on one idea at a time.\n\nSecond, show up consistently. Small steps add up.\n\nAnd third, enjoy the process. You’re learning something with every take.\n\nLet’s get into it.',updated:Date.now()-86400000},
 {id:'pitch',title:'The 60-second pitch',content:'Here’s the problem we kept running into.\n\n[Describe the problem in one clear sentence.]\n\nWe knew there had to be a better way. So we built one.\n\n[Introduce your idea and who it helps.]\n\nIt works in three simple steps.\n\n[Step one.]\n[Step two.]\n[Step three.]\n\nLess friction. More time for what matters.\n\nIf that sounds useful, I’d love to show you more.',updated:Date.now()-172800000}
];
export function words(text: string) { return text.trim() ? text.trim().split(/\s+/u).length : 0; }
export function timeLabel(seconds: number) { const n=Math.max(0,Math.floor(seconds));return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`; }
export function validScripts(value: unknown): value is Script[] {return Array.isArray(value) && value.length > 0 && value.length <= 500 && new Set(value.map(s=>s?.id)).size === value.length && value.every(s => typeof s?.id === 'string' && s.id.length > 0 && typeof s?.title === 'string' && typeof s?.content === 'string' && s.content.length <= 500000 && Number.isFinite(s.updated));}
export function normalizeSettings(value: unknown): Settings { const v=(value && typeof value==='object' ? value : {}) as Partial<Settings>;const bounded=(x:unknown,min:number,max:number,fallback:number)=>typeof x==='number' && Number.isFinite(x)?Math.min(max,Math.max(min,x)):fallback;return {speed:bounded(v.speed,10,120,defaults.speed),fontSize:bounded(v.fontSize,24,80,defaults.fontSize),lineHeight:bounded(v.lineHeight,1.2,2.2,defaults.lineHeight),width:bounded(v.width,45,95,defaults.width),mirror:typeof v.mirror==='boolean'?v.mirror:defaults.mirror,guide:typeof v.guide==='boolean'?v.guide:defaults.guide,countdown:bounded(v.countdown,0,10,defaults.countdown),theme:v.theme==='light'?'light':'dark'}; }
export function importScripts(text:string,filename:string): Script[] { if(text.length>(filename.toLowerCase().endsWith('.json')?32000000:2000000))throw new Error('Choose a script under 2 MB or a backup under 32 MB.');if(filename.toLowerCase().endsWith('.json')) {const parsed=JSON.parse(text); const data=Array.isArray(parsed)?parsed:parsed.scripts; if(!validScripts(data))throw new Error('This backup does not contain a valid CueFlow script library.');return data.map(s=>({...s,id:crypto.randomUUID(),updated:Date.now()}));}if(!/\.(txt|md)$/i.test(filename))throw new Error('Choose a .txt, .md, or CueFlow .json file.');if(text.length>500000)throw new Error('A script can contain up to 500,000 characters.');return [{id:crypto.randomUUID(),title:filename.replace(/\.(txt|md)$/i,'')||'Imported script',content:text,updated:Date.now()}]; }
